services:
  # For production mode, use:
  #   docker compose up
  prod:
    build: .
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - db-data:/app/db
      - media-data:/app/media
      - logs-data:/app/logs
    env_file:
      - .env
    environment:
      - HOST=0.0.0.0
      - FLASK_ENV=production
    command: python app.py

  # For development mode, use:
  #   docker compose up dev
  dev:
    build: .
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/app
      - db-data:/app/db
      - media-data:/app/media
      - logs-data:/app/logs
    env_file:
      - .env
    environment:
      - HOST=0.0.0.0
      - FLASK_ENV=development
    command: python app.py --reload

volumes:
  db-data:
  media-data:
  logs-data: 